from flask import Flask, render_template, send_file
import csv
from collections import defaultdict
import os
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
app = Flask(__name__)
_rf_model   = None      # RandomForestClassifier
_tfidf_vec  = None      # TfidfVectorizer (fit on training corpus)
_le         = None      # LabelEncoder for doubt labels
_model_ready = False

DOUBT_LABELS = [
    "Good Understanding",
    "Partial Understanding",
    "Incomplete Answer",
    "Concept Unclear",
    "Wrong Answer",
    "Confused with Regression",
    "Confused with Classification",
    "Confused with Clustering",
    "Confused with Neural Networks",
]
def _build_features(student_ans_list, correct_ans_list, vectorizer, is_train=False):
    """
    Builds feature matrix for the Random Forest:
      - TF-IDF cosine similarity score     (1 feature)
      - Student answer TF-IDF vector       (sparse → dense, top N dims)
    """
    pairs = [s + " " + c for s, c in zip(student_ans_list, correct_ans_list)]

    if is_train:
        tfidf_matrix = vectorizer.fit_transform(pairs)
    else:
        tfidf_matrix = vectorizer.transform(pairs)

    # Cosine similarity between student and correct answer
    sim_scores = []
    for s, c in zip(student_ans_list, correct_ans_list):
        try:
            mat = vectorizer.transform([s, c])
            score = cosine_similarity(mat[0:1], mat[1:2])[0][0]
        except Exception:
            score = 0.0
        sim_scores.append(score)
    dense = tfidf_matrix.toarray()
    max_cols = min(dense.shape[1], 100)
    dense = dense[:, :max_cols]

    sim_col = np.array(sim_scores).reshape(-1, 1)
    return np.hstack([sim_col, dense])
def train_model():
    """
    Reads the labelled CSV (generated by generate_data.py) and trains:
      - TfidfVectorizer  → converts text to feature vectors
      - RandomForestClassifier → predicts doubt tag from features
    Falls back gracefully if CSV is missing or has < 10 rows.
    """
    global _rf_model, _tfidf_vec, _le, _model_ready

    csv_path = "data/student_answers.csv"
    if not os.path.exists(csv_path):
        print("⚠️  Training CSV not found. Run generate_data.py first.")
        return

    student_ans_list, correct_ans_list, labels = [], [], []
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if "Doubt_Label" not in row or "Similarity_Score" not in row:
                # Old CSV without ML columns — skip model training
                print("⚠️  CSV missing ML columns. Regenerate with updated generate_data.py.")
                return
            student_ans_list.append(row["Student Answer"])
            correct_ans_list.append(row["Correct Answer"])
            labels.append(row["Doubt_Label"])
    if len(labels) < 10:
        print("⚠️  Not enough training rows (<10). Skipping model training.")
        return
    _le = LabelEncoder()
    y = _le.fit_transform(labels)

    # Build TF-IDF vectorizer & feature matrix
    _tfidf_vec = TfidfVectorizer(ngram_range=(1, 2), max_features=200,
                                 sublinear_tf=True)
    X = _build_features(student_ans_list, correct_ans_list,
                        _tfidf_vec, is_train=True)

    # Train Random Forest
    _rf_model = RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=42
    )
    _rf_model.fit(X, y)
    _model_ready = True
    print(f"✅ Random Forest trained — {len(labels)} samples, "
          f"{len(_le.classes_)} doubt classes")
train_model()
def evaluate_subjective(student_ans, correct_ans):
    """
    Returns a score 0–5 using TF-IDF cosine similarity.
    Unchanged from original interface; ML-powered internally.
    """
    try:
        vec = TfidfVectorizer()
        tfidf = vec.fit_transform([student_ans, correct_ans])
        similarity = cosine_similarity(tfidf[0:1], tfidf[1:2])[0][0]
        return round(similarity * 5, 2)
    except Exception:
        return 0.0
def tag_doubt(student_ans, correct_ans, topic):
    """
    Primary: uses the trained Random Forest to predict the doubt label.
    Fallback (if model not ready): lightweight rule-based tagger.
    """
    if _model_ready and _tfidf_vec is not None:
        try:
            X = _build_features([student_ans], [correct_ans], _tfidf_vec,
                                 is_train=False)
            pred = _rf_model.predict(X)
            return _le.inverse_transform(pred)[0]
        except Exception:
            pass   # fall through to rule-based
    student = student_ans.lower()

    if len(student.split()) <= 4:
        return "Incomplete Answer"

    if topic == "Regression" and "class" in student:
        return "Confused with Classification"
    if topic == "Classification" and "continuous" in student:
        return "Confused with Regression"
    if topic == "Clustering" and "supervised" in student:
        return "Misunderstood Clustering"
    if topic == "Neural Networks" and "storage" in student:
        return "Wrong Concept"

    keywords = correct_ans.lower().split()[:5]
    match = sum(1 for w in keywords if w in student)

    if match >= 3:
        return "Good Understanding"
    if match >= 1:
        return "Partial Understanding"
    return "Concept Unclear"
def load_data():
    students      = {}
    topic_scores  = defaultdict(list)
    answers       = defaultdict(list)

    with open("data/student_answers.csv", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        for row in reader:
            usn     = row["USN"]
            name    = row["Name"]
            topic   = row["Topic"]
            correct = row["Correct Answer"]
            student = row["Student Answer"]
            doubt = "N/A"
            if len(correct.split()) <= 3:
                if student.strip().lower() == correct.strip().lower():
                    score = 5
                    doubt = "Good Understanding"
                else:
                    score = 0
                    doubt = "Wrong Answer"
            else:
                score = evaluate_subjective(student, correct)
                doubt = tag_doubt(student, correct, topic)
            answers[usn].append({
                "question": row["Question"],
                "correct":  correct,
                "student":  student,
                "score":    score,
                "doubt":    doubt,
            })

            if usn not in students:
                students[usn] = {
                    "USN":    usn,
                    "Name":   name,
                    "Marks":  0,
                    "Total":  0,
                    "Result": "Pass",
                    "details": []
                }
            students[usn]["Marks"] += score
            students[usn]["Total"] += 5
            students[usn]["details"].append({
                "question": row["Question"],
                "correct":  correct,
                "student":  student,
                "score":    score,
                "doubt":    doubt,
            })

            topic_scores[topic].append(score)
    student_list = []
    passed = 0
    failed = 0
    for s in students.values():
        percent = (s["Marks"] / s["Total"]) * 100 if s["Total"] else 0
        if percent < 40:
            s["Result"] = "Fail"
            failed += 1
        else:
            s["Result"] = "Pass"
            passed += 1
        student_list.append(s)

    total = len(student_list)
    marks_list = [[s["Marks"]] for s in student_list]
    if len(marks_list) >= 3:
        kmeans = KMeans(n_clusters=3, random_state=0, n_init="auto")
        labels = kmeans.fit_predict(marks_list)

        centers    = kmeans.cluster_centers_.flatten()
        sorted_idx = centers.argsort()

        mapping = {
            sorted_idx[0]: "Low",
            sorted_idx[1]: "Medium",
            sorted_idx[2]: "High"
        }

        for i, s in enumerate(student_list):
            s["performance"] = mapping[labels[i]]
    else:
        for s in student_list:
            s["performance"] = "Unknown"
    topic_percent = {}
    for t, scores in topic_scores.items():
        avg      = sum(scores) / len(scores)
        weakness = 100 - ((avg / 5) * 100)
        topic_percent[t] = round(weakness, 2)

    return student_list, total, passed, failed, topic_percent, answers
@app.route("/")
@app.route("/login")
def home():
    return render_template("login.html")
@app.route("/teacher")
def teacher_dashboard():
    students, total, passed, failed, topics, _ = load_data()

    pass_percent = round((passed / total) * 100, 2) if total else 0
    top_3 = sorted(topics.items(), key=lambda x: x[1], reverse=True)[:3]

    return render_template(
        "teacher_dashboard.html",
        students=students,
        total=total,
        passed=passed,
        failed=failed,
        pass_percent=pass_percent,
        topics=topics,
        teacher_name="Mrs Malar",
        top_3=top_3
    )
@app.route("/students")
def students_page():
    students, _, _, _, _, _ = load_data()
    return render_template("students.html", students=students)
@app.route("/student/<usn>")
def student_dashboard(usn):
    students, _, _, _, _, answers = load_data()

    student = None
    for s in students:
        if s["USN"] == usn:
            student = s
            break
    if not student:
        return "Student not found"
    student_answers = answers.get(usn, [])
    return render_template(
        "student_dashboard.html",
        student=student,
        answers=student_answers
    )
@app.route("/download/<usn>")
def download(usn):
    students, _, _, _, _, answers = load_data()

    student = None
    for s in students:
        if s["USN"] == usn:
            student = s
            break

    if not student:
        return "Student not found"

    file_path = f"{usn}_report.pdf"

    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet

    doc    = SimpleDocTemplate(file_path)
    styles = getSampleStyleSheet()

    elements = []
    elements.append(Paragraph("Student Report", styles["Title"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph(f"Name: {student['Name']}",   styles["Normal"]))
    elements.append(Paragraph(f"USN: {student['USN']}",     styles["Normal"]))
    elements.append(Paragraph(f"Marks: {round(student['Marks'], 2)}", styles["Normal"]))
    elements.append(Paragraph(f"Result: {student['Result']}", styles["Normal"]))

    elements.append(Spacer(1, 20))
    for d in student["details"]:
        elements.append(Paragraph(f"Q: {d['question']}",       styles["Normal"]))
        elements.append(Paragraph(f"Your: {d['student']}",     styles["Normal"]))
        elements.append(Paragraph(f"Correct: {d['correct']}",  styles["Normal"]))
        elements.append(Paragraph(f"Doubt: {d['doubt']}",      styles["Normal"]))
        elements.append(Spacer(1, 10))
    doc.build(elements)
    return send_file(file_path, as_attachment=True)
if __name__ == "__main__":
    app.run(debug=True)
